// <auto-generated />
using GeoLearn.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoLearn.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226051845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoLearn.Api.Models.WorkObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("age_years");

                    b.Property<double?>("AreaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha");

                    b.Property<string>("CompartmentId")
                        .HasColumnType("text")
                        .HasColumnName("compartment_id");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,3006)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SourceSrid")
                        .HasColumnType("integer")
                        .HasColumnName("source_srid");

                    b.Property<string>("SpeciesCode")
                        .HasColumnType("text")
                        .HasColumnName("species_code");

                    b.HasKey("Id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("idx_work_objects_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("work_objects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
