// <auto-generated />
using GeoLearn.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoLearn.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303082538_AddMultiCategorySystem")]
    partial class AddMultiCategorySystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoLearn.Api.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_countries_code");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_name");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("main_categories", (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("main_category_id");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("sub_categories", (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.WorkObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("age_years");

                    b.Property<double?>("AreaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha");

                    b.Property<string>("CompartmentId")
                        .HasColumnType("text")
                        .HasColumnName("compartment_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,5234)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SourceSrid")
                        .HasColumnType("integer")
                        .HasColumnName("source_srid");

                    b.Property<string>("SpeciesCode")
                        .HasColumnType("text")
                        .HasColumnName("species_code");

                    b.HasKey("Id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("idx_work_objects_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("work_objects", (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.WorkObjectRow", b =>
                {
                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("age_years");

                    b.Property<double?>("AreaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha");

                    b.Property<double?>("AreaHaLive")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha_live");

                    b.Property<string>("CompartmentId")
                        .HasColumnType("text")
                        .HasColumnName("compartment_id");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geojson");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SourceSrid")
                        .HasColumnType("integer")
                        .HasColumnName("source_srid");

                    b.Property<string>("SpeciesCode")
                        .HasColumnType("text")
                        .HasColumnName("species_code");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.MainCategory", b =>
                {
                    b.HasOne("GeoLearn.Api.Models.Country", "Country")
                        .WithMany("MainCategories")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GeoLearn.Api.Models.SubCategory", b =>
                {
                    b.HasOne("GeoLearn.Api.Models.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("GeoLearn.Api.Models.Country", b =>
                {
                    b.Navigation("MainCategories");
                });

            modelBuilder.Entity("GeoLearn.Api.Models.MainCategory", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
