// <auto-generated />
using GeoLearn.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoLearn.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303061128_AddCountryFilters")]
    partial class AddCountryFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoLearn.Api.Models.CountryConfig", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country_name");

                    b.Property<string>("MainCategoryLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("main_category_label");

                    b.Property<string>("SubCategoryLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_category_label");

                    b.HasKey("CountryCode");

                    b.ToTable("country_configs", (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.WorkObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("age_years");

                    b.Property<double?>("AreaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha");

                    b.Property<string>("CompartmentId")
                        .HasColumnType("text")
                        .HasColumnName("compartment_id");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,5234)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SourceSrid")
                        .HasColumnType("integer")
                        .HasColumnName("source_srid");

                    b.Property<string>("SpeciesCode")
                        .HasColumnType("text")
                        .HasColumnName("species_code");

                    b.HasKey("Id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("idx_work_objects_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("work_objects", (string)null);
                });

            modelBuilder.Entity("GeoLearn.Api.Models.WorkObjectRow", b =>
                {
                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("age_years");

                    b.Property<double?>("AreaHa")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha");

                    b.Property<double?>("AreaHaLive")
                        .HasColumnType("double precision")
                        .HasColumnName("area_ha_live");

                    b.Property<string>("CompartmentId")
                        .HasColumnType("text")
                        .HasColumnName("compartment_id");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geojson");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SourceSrid")
                        .HasColumnType("integer")
                        .HasColumnName("source_srid");

                    b.Property<string>("SpeciesCode")
                        .HasColumnType("text")
                        .HasColumnName("species_code");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
